import { Metadata } from 'next';
import ProductsClient from './ProductsClient';
import FAQ from '@/components/global/sections/FAQ';

const ogTitle = "AI Property Design & Visualization Platform | Zlendo Realty";
const ogDescription = "From 2D floor plans to 3D designs, photorealistic renders, and immersive virtual walkthroughs — visualize your entire property with AI.";

export const metadata: Metadata = {
    title: ogTitle,
    description: "Design, visualize, style, render, and experience properties with Zlendo Realty's AI-powered platform. Create 3D floor plans, realistic renders, and virtual walkthroughs.",
    keywords: [
        "AI property design and visualization", "AI property design", "AI property visualization",
        "AI home design", "AI interior design", "AI floor planner", "AI floor plan generator",
        "2D to 3D floor plan converter", "2D floor plan to 3D", "AI room design",
        "AI room planner", "AI interior design software", "3D floor plan software",
        "AI architectural visualization", "AI 3D rendering", "AI rendering software",
        "photorealistic architectural rendering", "virtual property walkthrough",
        "360 virtual walkthrough real estate", "real estate visualization software", "AI real estate design software"
    ],
    openGraph: {
        title: ogTitle,
        description: ogDescription,
        url: 'https://zlendorealty.com/products',
        siteName: 'Zlendo Realty',
        images: [
            {
                url: 'https://zlendorealty.com/assets/og-image.jpg',
                width: 1200,
                height: 630,
            },
        ],
        type: 'website',
    }
};

const faqData = [
    {
        question: "What is Zlendo Realty?",
        answer: "Zlendo Realty is an AI-powered property design and visualization platform that helps users create floor plans, convert 2D layouts into 3D spaces, style interiors, visualize exteriors, generate realistic renders, and create immersive virtual walkthroughs."
    },
    {
        question: "What can I do with Zlendo Realty?",
        answer: "You can plan spaces in 2D and 3D, convert existing floor plans into 3D environments, experiment with interior styles, design interiors and exteriors, generate photorealistic renders, and create interactive 360° walkthroughs."
    },
    {
        question: "Can I use Zlendo Realty if I am not an architect?",
        answer: "Yes. The platform is designed for both professionals and people who want to visualize their own spaces. AI-assisted workflows can simplify many of the technical steps involved in planning and visualization."
    },
    {
        question: "Can I convert an existing 2D floor plan into 3D?",
        answer: "Yes. The 2D to 3D Converter is designed to recognize uploaded layouts and transform them into structured 3D spaces."
    },
    {
        question: "Can I customize the designs generated by AI?",
        answer: "Yes. Zlendo Realty's workflow allows you to modify layouts, furniture, materials, finishes, lighting, and design styles rather than treating AI output as a final result."
    },
    {
        question: "Can I create both interior and exterior designs?",
        answer: "Yes. The Interiors & Exteriors product combines interior visualization with exterior architecture and landscaping capabilities."
    },
    {
        question: "Can I create photorealistic renders?",
        answer: "Yes. Realistic Renders uses AI-powered rendering to generate photorealistic visuals and lets users make design changes through natural-language prompts."
    },
    {
        question: "Can clients explore my design virtually?",
        answer: "Yes. Virtual Walkthrough enables interactive 360° experiences so clients can explore the design and understand the space more intuitively."
    },
    {
        question: "Do I need expensive rendering hardware?",
        answer: "Zlendo Realty's Realistic Renders and Virtual Walkthrough workflows are browser-based, reducing the need for traditional high-end rendering hardware."
    },
    {
        question: "Who is Zlendo Realty for?",
        answer: "Zlendo Realty can be used by homeowners, architects, interior designers, builders, contractors, property developers, and real estate professionals who need faster ways to design, visualize, present, or market spaces."
    }
];

export default function ProductsPage() {
    return (
        <main>
            <script type="application/ld+json" dangerouslySetInnerHTML={{
                __html: JSON.stringify({
                    "@context": "https://schema.org",
                    "@type": "WebPage",
                    "url": "https://zlendorealty.com/products",
                    "name": ogTitle,
                    "description": ogDescription,
                    "publisher": {
                        "@type": "Organization",
                        "name": "Zlendo Realty"
                    }
                })
            }} />
            <script type="application/ld+json" dangerouslySetInnerHTML={{
                __html: JSON.stringify({
                    "@context": "https://schema.org",
                    "@type": "FAQPage",
                    "mainEntity": faqData.map(faq => ({
                        "@type": "Question",
                        "name": faq.question,
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": faq.answer
                        }
                    }))
                })
            }} />

            <ProductsClient />

            <section className="bg-white">
                <FAQ data={{ title: "Frequently Asked Questions", faqs: faqData }} />
            </section>
        </main>
    );
}
