import homePage from './homePage';
import siteSettings from './siteSettings';
import floorPlannerPage from './floorPlannerPage';
import twoDTo3DPage from './twoDTo3DPage';
import homeRemodelingPage from './homeRemodelingPage';
import roomStylerPage from './roomStylerPage';
import vastuPage from './vastuPage';
import interiorsExteriorsPage from './interiorsExteriorsPage';
import costEstimatorPage from './costEstimatorPage';
import realisticRendersPage from './realisticRendersPage';
import virtualWalkthroughPage from './virtualWalkthroughPage';
import businessPage from './businessPage';
import viewAllTemplatesPage from './viewAllTemplatesPage';
import tutorialsPage from './tutorialsPage';
import vrStudioPage from './vrStudioPage';
import apiSuitePage from './apiSuitePage';
import partnersPage from './partnersPage';
import contactPage from './contactPage';

export const schemaTypes = [homePage, siteSettings, floorPlannerPage, twoDTo3DPage, homeRemodelingPage, roomStylerPage, vastuPage, interiorsExteriorsPage, costEstimatorPage, realisticRendersPage, virtualWalkthroughPage, businessPage, viewAllTemplatesPage, tutorialsPage, vrStudioPage, apiSuitePage, partnersPage, contactPage];
