import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  groups: [
    { name: 'seo', title: '🔍 SEO & Meta' },
    { name: 'hero', title: '🏠 Hero Section' },
    { name: 'intelligence', title: '🧠 9D Intelligence Cards' },
    { name: 'features', title: '⚡ Feature Sections' },
    { name: 'comparison', title: '⚖️ Comparison Section' },
    { name: 'faq', title: '❓ FAQs' },
    { name: 'templates', title: '🏗️ Design Templates' },
    { name: 'cta', title: '🚀 Final CTA' },
  ],
  fields: [
    // Hidden Title for CMS Root ID
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      hidden: true,
      initialValue: 'Home Page'
    }),
    // ── SEO & Meta ────────────────────────────────────────────────────────
    defineField({
      name: 'seoTitle',
      title: 'Page Title (SEO)',
      type: 'string',
      group: 'seo',
      initialValue: 'AI Home & Office Design Software for Builders and Architects',
      description: 'The browser tab title and Google search result title.',
    }),
    defineField({
      name: 'seoDescription',
      title: 'Meta Description (SEO)',
      type: 'text',
      rows: 3,
      group: 'seo',
      initialValue: 'Zlendo Realty AI Floor Planner and 2D-to-3D Designs in Minutes. All-in-One Software for Architects, Builders, Interior Designers, and Vastu Consultants. Start Your Free Trial Now!',
      description: 'Shows in Google search results below the title. Keep under 160 chars.',
    }),
    defineField({
      name: 'ogTitle',
      title: 'OpenGraph Title (Social Share)',
      type: 'string',
      group: 'seo',
      initialValue: 'AI-Powered Home & Office Design Software | Zlendo Realty',
    }),
    defineField({
      name: 'ogDescription',
      title: 'OpenGraph Description (Social Share)',
      type: 'text',
      rows: 2,
      group: 'seo',
      initialValue: 'Create professional 2D and 3D floor plans in minutes with Zlendo Realty AI. The all-in-one design software for Architects, Builders, Interior designers, and Vastu Consultants. Start your free trial today!',
    }),
    defineField({
      name: 'ogImage',
      title: 'OpenGraph Image (Social Share)',
      type: 'image',
      group: 'seo',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),

    // ── Hero ──────────────────────────────────────────────────────────────
    defineField({
      name: 'heroBadgeText',
      title: 'Hero Badge Text',
      type: 'string',
      group: 'hero',
      initialValue: 'Create with Confidence',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title (before highlight)',
      type: 'string',
      group: 'hero',
      initialValue: 'Design Smarter.',
    }),
    defineField({
      name: 'heroTitleHighlight',
      title: 'Hero Title Highlight (teal italic)',
      type: 'string',
      group: 'hero',
      initialValue: 'Build Faster.',
    }),
    defineField({
      name: 'heroTitleAfter',
      title: 'Hero Title (after highlight)',
      type: 'string',
      group: 'hero',
      initialValue: 'Deliver Better.',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      type: 'text',
      rows: 3,
      group: 'hero',
      initialValue:
        'Powerful Civil Plan & Interior Design Software for Professionals and Individuals. Zlendo Realty helps you create accurate 2D plans, stunning 3D designs, and complete interior layouts—all from one easy-to-use platform.',
    }),
    defineField({
      name: 'heroPrimaryCtaLabel',
      title: 'Primary CTA Button Label',
      type: 'string',
      group: 'hero',
      initialValue: 'Design Home for Free',
    }),
    defineField({
      name: 'heroPrimaryCtaLink',
      title: 'Primary CTA Button Link',
      type: 'string',
      group: 'hero',
      initialValue: 'https://app.zlendorealty.com/register',
      description: 'Where the primary CTA button leads to.',
    }),
    defineField({
      name: 'heroSecondaryCtaLabel',
      title: 'Secondary CTA Button Label',
      type: 'string',
      group: 'hero',
      initialValue: 'Schedule Your Business Demo',
    }),
    defineField({
      name: 'heroSecondaryCtaLink',
      title: 'Secondary CTA Button Link',
      type: 'string',
      group: 'hero',
      initialValue: '/in/business#demo-form',
      description: 'Where the secondary CTA button leads to. Can be a relative path.',
    }),

    // ── 9D Intelligence ────────────────────────────────────────────────────
    defineField({
      name: 'intelligenceBadgeText',
      title: '9D Section Badge Text',
      type: 'string',
      group: 'intelligence',
      initialValue: 'Proprietary 9D Framework',
    }),
    defineField({
      name: 'intelligenceSectionTitle',
      title: 'Intelligence Section Title (Before)',
      type: 'string',
      group: 'intelligence',
      initialValue: 'The Intelligence',
    }),
    defineField({
      name: 'intelligenceSectionTitleHighlight',
      title: 'Intelligence Section Title Highlight (Teal)',
      type: 'string',
      group: 'intelligence',
      initialValue: 'behind',
    }),
    defineField({
      name: 'intelligenceSectionTitleAfter',
      title: 'Intelligence Section Title (After)',
      type: 'string',
      group: 'intelligence',
      initialValue: 'your dream home.',
    }),
    defineField({
      name: 'intelligenceSectionSubtitle',
      title: 'Intelligence Section Subtitle',
      type: 'string',
      group: 'intelligence',
      initialValue: 'Swipe to explore how our 9D engine guarantees total peace of mind.',
    }),
    defineField({
      name: 'dimensionSuffix',
      title: 'Dimension Suffix (e.g. Dimension)',
      type: 'string',
      group: 'intelligence',
      initialValue: 'Dimension',
    }),
    defineField({
      name: 'intelligenceDimensions',
      title: '9D Intelligence Cards',
      type: 'array',
      group: 'intelligence',
      of: [
        {
          type: 'object',
          name: 'dimensionItem',
          fields: [
            defineField({ name: 'id', title: 'Dimension ID (e.g. 1D)', type: 'string' }),
            defineField({ name: 'title', title: 'Title', type: 'string' }),
            defineField({ name: 'shortDesc', title: 'Short Description', type: 'string' }),
            defineField({ name: 'longDesc', title: 'Long Description', type: 'text' }),
            defineField({ name: 'benefit', title: 'Benefit Label', type: 'string' }),
            defineField({ name: 'cta', title: 'CTA Button Text', type: 'string' }),
            defineField({ name: 'link', title: 'CTA Link', type: 'string' }),
            defineField({
              name: 'iconName',
              title: 'Icon Name (Lucide)',
              type: 'string',
              description: 'One of: Ruler, Box, Eye, Image, Video, Calculator, Palette, Sparkles, Compass',
              options: {
                list: [
                  { title: 'Ruler', value: 'Ruler' },
                  { title: 'Box', value: 'Box' },
                  { title: 'Eye', value: 'Eye' },
                  { title: 'Image', value: 'Image' },
                  { title: 'Video', value: 'Video' },
                  { title: 'Calculator', value: 'Calculator' },
                  { title: 'Palette', value: 'Palette' },
                  { title: 'Sparkles', value: 'Sparkles' },
                  { title: 'Compass', value: 'Compass' },
                ],
              },
            }),
            defineField({ name: 'colorClass', title: 'Tailwind Color Class (e.g. text-blue-500)', type: 'string' }),
            defineField({ name: 'bgClass', title: 'Tailwind BG Class (e.g. bg-blue-500)', type: 'string' }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'id' },
          },
        },
      ],
      initialValue: [
        {
          id: '1D',
          title: 'Precision Floor Planning',
          shortDesc: '2D CAD Accuracy',
          longDesc: 'Create builder-ready, engineering-grade 2D floor plans with to-the-millimeter precision. Design layouts that meet municipal standards instantly.',
          iconName: 'Ruler',
          colorClass: 'text-blue-500',
          bgClass: 'bg-blue-500',
          benefit: 'Construction Ready',
          cta: 'Start Sketching',
          link: '/in/products/floor-planner',
        },
        {
          id: '2D',
          title: 'Automated 3D Conversion',
          shortDesc: 'Instant Modeling',
          longDesc: 'Our engine interprets your 2D lines and textures, extruding them into a fully-fleshed 3D model with furniture, lighting, and finishes.',
          iconName: 'Box',
          colorClass: 'text-indigo-500',
          bgClass: 'bg-indigo-500',
          benefit: 'Instant Visualization',
          cta: 'Start Convert to 3D',
          link: '/in/products/2d-to-3d',
        },
        {
          id: '3D',
          title: 'Interactive Walkthrough',
          shortDesc: 'Immersive Exploration',
          longDesc: 'Walk through your future home as if you were there. Open doors, inspect corners, and feel the space in first-person view.',
          iconName: 'Eye',
          colorClass: 'text-zlendo-teal',
          bgClass: 'bg-zlendo-teal',
          benefit: 'True-to-Life Experience',
          cta: 'Experience It Live',
          link: '/in/products/virtual-walkthrough',
        },
        {
          id: '4D',
          title: 'Photorealistic Rendering',
          shortDesc: '4K Visualization',
          longDesc: 'Generate magazine-quality static renders with ray-traced lighting, shadows, and reflections to see the true beauty of your design.',
          iconName: 'Image',
          colorClass: 'text-purple-500',
          bgClass: 'bg-purple-500',
          benefit: 'Stunning Presentation',
          cta: 'Start Render Realistic',
          link: '/in/products/realistic-renders',
        },
        {
          id: '5D',
          title: 'Cinematic Video',
          shortDesc: 'Automated Tours',
          longDesc: 'Create smooth, cinematic video tours of your property automatically. Perfect for presentations and social media sharing.',
          iconName: 'Video',
          colorClass: 'text-pink-500',
          bgClass: 'bg-pink-500',
          benefit: 'Engaging Storytelling',
          cta: 'Build Video Tour',
          link: '/in/products/realistic-renders',
        },
        {
          id: '6D',
          title: 'Cost Engine',
          shortDesc: 'Real-Time BOQ',
          longDesc: 'Get an instant Bill of Quantities (BOQ) with local pricing. Know accurately how much cement, steel, and paint you need.',
          iconName: 'Calculator',
          colorClass: 'text-emerald-600',
          bgClass: 'bg-emerald-600',
          benefit: 'Budget Certainty',
          cta: 'Check Project Cost',
          link: '/in/products/cost-estimator',
        },
        {
          id: '7D',
          title: 'Material Library',
          shortDesc: 'Infinite Customization',
          longDesc: 'Access thousands of real-world materials. Swap tiles, paints, and fabrics instantly to find the perfect combination.',
          iconName: 'Palette',
          colorClass: 'text-amber-500',
          bgClass: 'bg-amber-500',
          benefit: 'Design Freedom',
          cta: 'Explore Materials',
          link: 'https://zlendo-designlibrary.zlendorealty.com/',
        },
        {
          id: '8D',
          title: 'AI Style Inspiration',
          shortDesc: 'Generative Design',
          longDesc: 'Stuck on ideas? Let our AI suggest themes like "Modern Minimalist" or "Traditional Warm" tailored to your room layout.',
          iconName: 'Sparkles',
          colorClass: 'text-rose-500',
          bgClass: 'bg-rose-500',
          benefit: 'Instant Creativity',
          cta: 'Get AI Ideas',
          link: '/in/products/floor-planner',
        },
        {
          id: '9D',
          title: 'Vastu Recommendations',
          shortDesc: 'Ancient Wisdom',
          longDesc: 'Get instant AI-driven Vastu compliance scores. Detect energy imbalances and receive corrective suggestions for harmony.',
          iconName: 'Compass',
          colorClass: 'text-orange-500',
          bgClass: 'bg-orange-500',
          benefit: 'Energy Harmony',
          cta: 'Run Vastu Check',
          link: '/in/products/vastu',
        },
      ],
    }),

    // ── Feature Sections ───────────────────────────────────────────────────
    defineField({
      name: 'howToSectionTitle',
      title: '"How To Design" Section Title',
      type: 'string',
      group: 'features',
      initialValue: 'How to design a home online for free',
    }),
    defineField({
      name: 'howToSectionSubtitle',
      title: '"How To Design" Subtitle',
      type: 'string',
      group: 'features',
      initialValue: 'Design your 2BHK, pooja room, or bungalow easily with Zlendo Realty. Get Vastu-friendly plans & realistic 3D views!',
    }),
    defineField({
      name: 'features',
      title: 'Feature Sections',
      type: 'array',
      group: 'features',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'section', title: 'Section Badge (e.g. Plan & Design)', type: 'string' }),
            defineField({ name: 'title', title: 'Feature Title', type: 'string' }),
            defineField({ name: 'description', title: 'Description', type: 'text' }),
            defineField({
              name: 'howItWorks',
              title: 'How It Works Steps',
              type: 'array',
              of: [{ type: 'string' }],
            }),
            defineField({ name: 'cta', title: 'CTA Text', type: 'string' }),
            defineField({ name: 'ctaLink', title: 'CTA Link URL', type: 'string', description: 'Leave empty to default to signup URL.' }),
            defineField({
              name: 'imageUrl',
              title: 'Feature Image',
              type: 'image',
              options: { hotspot: true },
              fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
            }),
            defineField({ name: 'reverse', title: 'Reverse Layout (image left)', type: 'boolean', initialValue: false }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'section' },
          },
        },
      ],
    }),

    // ── Comparison Section ─────────────────────────────────────────────────
    defineField({
      name: 'comparisonBadgeText',
      title: 'Comparison Badge Text',
      type: 'string',
      group: 'comparison',
      initialValue: 'Peace of Mind',
    }),
    defineField({
      name: 'comparisonTitle',
      title: 'Comparison Section Title',
      type: 'string',
      group: 'comparison',
      initialValue: 'Your Dream Design',
    }),
    defineField({
      name: 'comparisonTitleHighlight',
      title: 'Comparison Title Highlight (gradient text)',
      type: 'string',
      group: 'comparison',
      initialValue: 'made Easy',
    }),
    defineField({
      name: 'comparisonSubtitle',
      title: 'Comparison Subtitle',
      type: 'string',
      group: 'comparison',
      initialValue: 'Why 12,000+ modern homeowners chose Zlendo Realty over traditional guesswork.',
    }),
    defineField({
      name: 'comparisonOldWayLabel',
      title: 'Comparison "Old Way" Label',
      type: 'string',
      group: 'comparison',
      initialValue: 'Old Way',
    }),
    defineField({
      name: 'comparisonNewWayLabel',
      title: 'Comparison "New Way" Label',
      type: 'string',
      group: 'comparison',
      initialValue: 'Zlendo Realty Way',
    }),
    defineField({
      name: 'comparisonRows',
      title: 'Comparison Rows',
      type: 'array',
      group: 'comparison',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'title', title: 'Title', type: 'string' }),
            defineField({ name: 'oldWay', title: 'Old Way (crossed-out)', type: 'string' }),
            defineField({ name: 'newWay', title: 'Zlendo Realty Way', type: 'string' }),
            defineField({ name: 'gradient', title: 'Tailwind Gradient (e.g. from-purple-500 to-pink-400)', type: 'string' }),
            defineField({
              name: 'iconName',
              title: 'Icon Name (Lucide)',
              type: 'string',
              description: 'One of: Layers, Palette, Box, Zap',
              options: {
                list: [
                  { title: 'Layers', value: 'Layers' },
                  { title: 'Palette', value: 'Palette' },
                  { title: 'Box', value: 'Box' },
                  { title: 'Zap', value: 'Zap' },
                ],
              },
            }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'newWay' },
          },
        },
      ],
    }),

    // ── FAQ ────────────────────────────────────────────────────────────────
    defineField({
      name: 'faqSectionTitle',
      title: 'FAQ Section Title',
      type: 'string',
      group: 'faq',
      initialValue: 'Frequently Asked Questions',
    }),
    defineField({
      name: 'faqs',
      title: 'FAQ Items',
      type: 'array',
      group: 'faq',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'question', title: 'Question', type: 'string' }),
            defineField({ name: 'answer', title: 'Answer', type: 'text' }),
          ],
          preview: {
            select: { title: 'question' },
          },
        },
      ],
    }),
 
    // ── Design Templates ───────────────────────────────────────────────────
    defineField({
      name: 'templatesSectionTitle',
      title: 'Templates Section Title',
      type: 'string',
      group: 'templates',
      initialValue: 'A wide range of home design',
    }),
    defineField({
      name: 'templatesSectionTitleHighlight',
      title: 'Templates Section Title Highlight',
      type: 'string',
      group: 'templates',
      initialValue: 'ideas available!',
    }),
    defineField({
      name: 'templatesSectionSubtitle',
      title: 'Templates Section Subtitle',
      type: 'text',
      rows: 3,
      group: 'templates',
      initialValue: 'Looking for inspiration for your pooja room, balcony, or open-plan living area? Explore ready-made design templates for living rooms, bedrooms, kitchens, bathrooms, and more — thoughtfully designed for Indian homes and lifestyles.',
    }),
    defineField({
      name: 'templatesButtonLabel',
      title: 'Templates Button Label',
      type: 'string',
      group: 'templates',
      initialValue: 'View all templates',
    }),
    defineField({
      name: 'templatesNoDataText',
      title: 'Templates "No Data" Text',
      type: 'string',
      group: 'templates',
      initialValue: 'No designs available for this category.',
    }),

    // ── Final CTA ─────────────────────────────────────────────────────────
    defineField({
      name: 'ctaTitle',
      title: 'Final CTA Title',
      type: 'string',
      group: 'cta',
      initialValue: 'Start designing your house with Zlendo Realty',
    }),
    defineField({
      name: 'ctaSubtitle',
      title: 'Final CTA Subtitle',
      type: 'string',
      group: 'cta',
      initialValue: 'Draw a floor plan and create a 3D home design in 10 min.',
    }),
    defineField({
      name: 'ctaButtonLabel',
      title: 'Final CTA Button Label',
      type: 'string',
      group: 'cta',
      initialValue: 'Get Started For Free',
    }),
    defineField({
      name: 'ctaButtonLink',
      title: 'Final CTA Button Link',
      type: 'string',
      group: 'cta',
      initialValue: 'https://app.zlendorealty.com/register',
    }),
    defineField({
      name: 'ctaImageUrl',
      title: 'CTA Section Image',
      type: 'image',
      group: 'cta',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
  ],
  preview: {
    select: { title: 'seoTitle' },
    prepare({ title }) {
      return { title: title || 'Home Page' }
    }
  },
});
